version: "2"
services:  
    database:
        image: mysql
        container_name: mysql
        command: mysqld --user=root --verbose
        volumes:
        - ./sql/rootfs/:/docker-entrypoint-initdb.d
        ports:
        - "3306:3306"
        environment:
            MYSQL_DATABASE: "covidsos"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    flask:
        container_name: flask
        build: flask
        volumes: 
        - "../:/app"
        - "../deps:/usr/local/lib/python3.6/dist-packages"
        ports:
            - "5000:5000"
            - "4000:4000"
        command: bash -c "pip3 install -r requirements.txt && supervisord -c supervisord-local.conf"
        environment: 
            FLASK_ENV: "development"
            FLASK_APP: apis.py
            HOST: '0.0.0.0'
            REDISHOST: redis
        depends_on: 
        - database
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379